### ISSUE TITLE
Contract Spec

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-contract-sdk#42]
This description is updated with the resolution:

The design is here: https://github.com/stellar/rs-stellar-contract-sdk/issues/42#issuecomment-1143937788

The list of things to do now are here (https://github.com/stellar/rs-stellar-contract-sdk/issues/42#issuecomment-1146455941):

- [x] stellar/rs-stellar-contract-sdk#114
- [x] stellar/rs-stellar-contract-sdk#115
- [x] stellar/rs-stellar-contract-sdk#116
- [x] https://github.com/stellar/rs-stellar-contract-sdk/issues/24
- [x] stellar/rs-stellar-contract-sdk#117
- [ ] https://github.com/stellar/rs-stellar-contract-sdk/issues/153
- [ ] https://github.com/stellar/rs-stellar-contract-sdk/issues/168
- [ ] stellar/rs-stellar-contract-sdk#118
- [x] stellar/stellar-contract-cli#6
- [ ] stellar/stellar-contract-cli#7
- [ ] stellar/stellar-contract-cli#8
- [ ] https://github.com/stellar/rs-stellar-contract-sdk/issues/142

**Comment by leighmcculloch** [comment]
I looked through these links, and I think we can do the simplest thing for now, which given our alignment and use of Rust is probably a toml file that looks something like:

```toml
[contract]

[[fn]]
symbol = "add32"
args = ["i32", "i32"]
return_type = "i32"

[[fn]]
symbol = "add64"
args = ["i64", "i64"]
return_type = "i64"

[[fn]]
symbol = "hndmsg"
args = ["obj:binary"]
return_type = "bool"
```

The above example provides the fields as specified in [CAP-47](https://stellar.org/protocol/cap-47) (@sisuresh).

The example assumes that types can be referenced using the `SCValType` definition in CAP-47, here expressed in an abbreviated form but otherwise consistent.

**Comment by leighmcculloch** [comment]
A simple format like this will be relatively easy to convert into XDR when deploying, but nothing about it necessarily helps us validate a contract function, since a contract function implements itself its conversion logic and so that can only be tested by executing the function, but no general test can confirm that part of a contract is working correctly without potentially executing invalid values that cause the contract to fail for other reasons.

**Comment by leighmcculloch** [comment]
A large part of the problem of verifying code written by developers is that our contracts currently take the following shape. Since the inputs are all untyped RawVals there's not a lot we can do to validate the types that the functions will use internally.
<img width="469" alt="Screen Shot 2022-05-26 at 3 46 07 PM" src="https://user-images.githubusercontent.com/351529/170591858-995d7df3-e851-44d6-87a3-78a3a417f005.png">

Ideally we end up with code looking like this snippet, where function arguments are typed, it is easy to validate that a function matches a signature, and the conversion is largely hidden from the developer. We had a prototype of supporting this with a procedural macro in https://github.com/stellar/rs-stellar-contract-sdk/pull/9. However, this doesn't leverage the Rust compiler to actually do that verification, we'd probably have to use `syn` and some other crates to parse the signature and match it to the manifest.
<img width="469" alt="Screen Shot 2022-05-26 at 3 46 28 PM" src="https://user-images.githubusercontent.com/351529/170592021-ea363f27-08d5-437b-bae7-5c0b24745bf5.png">

To leverage the Rust compiler to validate the shape of the functions implemented we need to use traits to do something like the below. I think this gets us most things we want, except it isn't particularly portable to other languages. But it is compelling that a developer could share a trait and others could implement it, and everybody would be using the compiler they already have on their systems to guarantee compatibility. Of course, this would require us to use a procedural macro, like on the example above, to generate extern fns.
<img width="469" alt="Screen Shot 2022-05-26 at 3 46 50 PM" src="https://user-images.githubusercontent.com/351529/170592227-f869dd0f-a7d7-4564-af29-ef7732a360c4.png">

**Comment by graydon** [comment]
I think there's a plausible (and possibly kinda forced-on-us) point in the design space where "an interface" is defined as either an XDR manifest or a (bijectively mapped) Rust trait, and we have a proc macro on a unit type (or an impl?) that emits a bunch of global #[no_mangle] pub fns that receive RawVals and call through to to the associated methods on the unit type, with each arg run through into() or try_into(). I'd be willing to see how horrible that is. It's macros which I don't love, but I don't see a lot of other options at this point.

**Comment by leighmcculloch** [comment]
I agree, that's where I'm landing too. When I prototyped this previously in #9 the only benefit was to remove some boilerplate, but now the benefit is greater as it would include the trait being a way developers can share their contract interfaces.

I'm going to prototype this and then we can review it and see how bad the tradeoffs are.

**Comment by paulbellamy** [comment]
You don't really need the impl there, afaict. You could just implement the contract as the default methods on the trait. e.g.
```rust
#[stellar::contract]
pub trait AddContract {
  fn add(_e: Env, a: i64, b: i64) -> i64 {
    a + b
  }
}
```

**Comment by paulbellamy** [comment]
Would the typecasting wrapper @graydon suggested need to be a macro? Could it be a sort of runtime within wasm, that loads up the contract code, introspects it, and casts? Ah, no. because it would need the type signatures which are only available at compile time.

**Comment by leighmcculloch** [comment]
> You don't really need the impl there, afaict.

To test the contract an impl will be required. Developer may as well write it that way. It also makes sharing the trait easier since you can copy and paste it anywhere without the impl. The moment the impl lives in the trait you can't do that.

**Comment by leighmcculloch** [comment]
@paulbellamy and I discussed this more today and I'm working towards something like the following diagram:

- Rust trait is the source of the interface.
- XDR is the common language all components speak.
- CLI turns the XDR manifest into interfaces and code in client languages. (There may be other dapp tooling that also does this in other ways.)
- A tool generates the XDR, either:
  - The macro I'm building in #109 will generate a custom wasm section that contains the XDR, such that the generation of the XDR occurs as part of compile time.
  - Some other tool, such as the CLI, will create the XDR from a Rust trait.

![manifest-parts](https://user-images.githubusercontent.com/351529/171467925-53eee5d3-eb59-4249-9c99-dde5b1b0ce25.png)

**Comment by leighmcculloch** [comment]
@paulbellamy and I also discussed who the stakeholders/users are, and the use cases, and came up with the following relationships and technologies that will possibly touch it:
![stakeholders excalidraw](https://user-images.githubusercontent.com/351529/171473353-b023a4f3-8707-455a-a1f2-0fdae6866429.png)

**Comment by leighmcculloch** [comment]
Conversations with @paulbellamy and @jonjove have expanded this work in a few things, so I'm going to open issues for each of them and close this issue as I think we have a reasonably good high-level plan now:

- [ ] Add impl attribute macro that writes out extern fns that wrap the impl fns, and unwrap/wrap RawVals.

- [ ] Define XDR for manifest (take from CAP-47).

- [ ] Experiment with custom sections and if we can store something like XDR in them. See if it is then also easy to extract that section, and strip that section, after compile.
- [ ] Add a trait attribute macro that:
  - [ ] Add trait attribute macro that generates an XDR value that describes the functions of the trait, and inserts that XDR as a custom section in the final wasm.
  - [ ] Add trait attribute macro that generates a cross-contract calling impl.

- [ ] Add CLI command that extracts XDR from .wasm.
- [ ] Add CLI command that generates a Rust trait from .wasm.

**Comment by leighmcculloch** [comment]
All the plans live in subissues now, and I'm going to close this parent issue to continue to use the subissues. All issues relating to this will be prefixed with `Contract Spec: `.
